server_replay: [
"hints_flows/variety-com",
"hints_flows/axomjobs-in",
"hints_flows/beautydea-it",
"hints_flows/berlinomagazine-com",
"hints_flows/braunshop-co-uk",
"hints_flows/caribbean-beat-com",
"hints_flows/crawleynews-co-uk",
"hints_flows/creativebloq-com",
"hints_flows/freeagent",
"hints_flows/dallasnews-com",
"hints_flows/dell-com",
"hints_flows/dictionary-com",
"hints_flows/ecomputertips-com",
"hints_flows/express-co-uk",
"hints_flows/foundationfairy-com",
"hints_flows/gardeninglovy-com",
"hints_flows/gettersiida-net",
"hints_flows/home-pl",
"hints_flows/iamvenezuela-com",
"hints_flows/jezebel-com",
"hints_flows/lululemon-com",
"hints_flows/manchestereveningnews-co-uk",
"hints_flows/marketwatch-com",
"hints_flows/multimetertools-com",
"hints_flows/nationalreview-com",
"hints_flows/ncaa-com",
"hints_flows/nwsource-com",
"hints_flows/opumo-net",
"hints_flows/tnscolaire-com",
"hints_flows/simplylakita-com",
"hints_flows/skynewsarabia-com",
"hints_flows/stern-de",
"hints_flows/tebasnan-com",
"hints_flows/teleseryeonline-su",
"hints_flows/thefreelancemovement-com",
"hints_flows/therecipespk-com",
"hints_flows/timesofmalta-com",
"hints_flows/vivahr-com",
"hints_flows/westernunion-com",
"hints_flows/writeawriting-com",
]

server_replay_nopop: true
server_replay_kill_extra: true
save_stream_file: "output/flows_hints"

